### ISSUE TITLE
Missing Binaries error

### ISSUE THREAD

**Issue by kaedenjames** [themill/DeckLinkMedia#9]
"Binaries for the 'DeckLinkMedia' plugin are missing or incompatible with the current engine version."

Anyone have this issue? Is there something I'm doing wrong with the plugin installation? I'm just adding the downloaded folder into the Plugins folder for my UE4 project. The plugin shows up and can be 'enabled', but on restart I just get a Binaries error.

**Comment by clarksbrother** [comment]
You need to have Visual Studio 2017 installed (then create a Visual C++ project which will force it to download the necessary libraries). Then try running - that's what worked for me.

**Comment by num3ric** [comment]
Resolved since ef70978c3fe3ef1a65d8232074a4d3aaaca11146, now updated to 4.20.
